CREATE TABLE Continent
 (
 Id INT NOT NULL PRIMARY KEY IDENTITY,
 Name NVARCHAR(50)
 )

CREATE TABLE Country 
 (
  Id INT NOT NULL PRIMARY KEY IDENTITY,
  Name NVARCHAR(50),
  ContinentId INT NOT NULL,
  CONSTRAINT FK_Continent FOREIGN KEY(ContinentId) REFERENCES Continent (Id)
 )

CREATE TABLE Town
 (
  Id INT NOT NULL PRIMARY KEY IDENTITY,
  Name NVARCHAR(50),
  CountryId INT NOT NULL,
  CONSTRAINT FK_Country FOREIGN KEY(CountryId) REFERENCES Country (Id)
 )

CREATE TABLE Address
 (
  Id INT NOT NULL PRIMARY KEY IDENTITY,
  AddressText NVARCHAR(50),
  TownId INT NOT NULL,
  CONSTRAINT FK_Town FOREIGN KEY(TownId) REFERENCES Town (Id)
 )

CREATE TABLE Person
 (
  Id INT NOT NULL PRIMARY KEY IDENTITY,
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL,
  AddressId INT NOT NULL,
  CONSTRAINT FK_Address FOREIGN KEY (AddressId) REFERENCES Address (Id)
 )