ALTER TABLE Employees
ADD CityId INT FOREIGN KEY REFERENCES Cities (Id)

ALTER TABLE Suppliers
ADD CityId INT FOREIGN KEY REFERENCES Cities (Id)

ALTER TABLE Customers 
ADD CityId INT FOREIGN KEY REFERENCES Cities (Id)