INSERT INTO Countries (Name)

SELECT DISTINCT Country FROM Employees WHERE Country IS NOT NULL
UNION
SELECT DISTINCT Country FROM Suppliers WHERE Country IS NOT NULL
UNION 
SELECT DISTINCT Country FROM Customers WHERE Country IS NOT NULL
UNION
SELECT DISTINCT ShipCountry FROM Orders WHERE ShipCountry IS NOT NULL